// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    copy: typeof import('./components/AppBar copy.vue')['default']
    CountNumber: typeof import('./components/CountNumber.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ListMenu: typeof import('./components/ListMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Welcome: typeof import('./components/Welcome.vue')['default']
  }
}
