/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    copy: typeof import('./components/AppBar copy.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ListMenu: typeof import('./components/ListMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Welcome: typeof import('./components/Welcome.vue')['default']
  }
}
